### ISSUE TITLE
It looks like zone.js is not needed

### ISSUE THREAD

**Issue by geyang** [johnlindquist/intro-to-angular2#5]
Hi John,

I didn't see an explicit reference to the zone.js dependency in the code. Does this mean the zone.js library is not needed anymore, and is superseded by the `angular2-polyfill.js` in the `angular2/bundle`?

Thanks for this class!
Ge

**Comment by johnlindquist** [comment]
Yup.

**Comment by geyang** [comment]
Thanks! :)
